### PR TITLE
Empty Rails Engine.

### PR DESCRIPTION
**Pull request by josephbridgwaterrowe**
Setup blank Rails Engine (with RSpec and rubocop, et al).

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Looks good. Its just a generic setup.

**Comment by michaelachrisco** [comment]
You can go ahead and merge.

**Comment by josephbridgwaterrowe** [comment]
Do you now want to do the honor?

**Comment by michaelachrisco** [comment]
I would love to but you are the owner :)

**Comment by josephbridgwaterrowe** [comment]
Whoops, you've been added.

**Pull request merged**
